from .compare_marginal_hists import compare_hist_real_vs_generated as hist_real_vs_generated
from .compare_evolution_marginal_hists import compare_evolution_hists_real_vs_generated as evolution_hists_real_vs_generated
